# Generated by Django 4.2 on 2023-04-07 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_recomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recomment',
        ),
    ]
